# This configuration file is for **development** setup. For production, refer to
# docker-compose.production.yml.
version: '3'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy:latest
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - app
    ports:
      - "80:80"
  app:
    build: .
    depends_on:
      - redis
    ports:
      - "5000"
    environment:
      IP: "0.0.0.0"
      VIRTUAL_HOST: localhost
      VIRTUAL_PORT: 5000
      REDIS_HOST: "redis"
      REDIS_PORT: 6379
  redis:
    image: redis:4.0-alpine
    ports:
      - "6379:6379"